steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/aawaz-uat/dev-awaz-backend-web:$COMMIT_SHA', '.']
# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/aawaz-uat/dev-aawaz-backend-web:$COMMIT_SHA']

